name: Coverage
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate
        run: swift test --enable-code-coverage --parallel
      - name: Export Coverage
        uses: mattpolzin/swift-codecov-action@0.6.0
