name: Coverage
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute
        run: swift test --enable-code-coverage --parallel
      - name: Locate Coverage Files
        run: echo "CODECOV_DIR=$(swift test --show-codecov-path | xargs dirname)" >> $GITHUB_ENV
      - name: Export Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          directory: ${{ env.CODECOV_DIR }}
          verbose: true
